"""去内置化迁移的默认信号种子 (一次性写入用户数据目录)。

仅在 ``data/user_data/custom_signals`` 为空且从未种子化时写入一次
(``.seeded_v1`` 标记防重); 写入后即为普通用户定义, 可编辑可删除。
单一事实源: tests/fixtures/custom_signals 的 JSON 与此同内容。
"""
from __future__ import annotations

SEED_SIGNALS: list[dict] = [
    {'id': 'boll_breakdown_lower',
     'name': '跌破布林下轨',
     'kind': 'both',
     'timeframe': 'daily',
     'enabled': True,
     'conditions': [{'left': 'close',
                     'op': '<',
                     'right': 'field:boll_lower',
                     'leftDays': 0,
                     'rightDays': 0}],
     'column': 'signal_boll_breakdown_lower'},
    {'id': 'boll_breakout_upper',
     'name': '突破布林上轨',
     'kind': 'both',
     'timeframe': 'daily',
     'enabled': True,
     'conditions': [{'left': 'close',
                     'op': '>',
                     'right': 'field:boll_upper',
                     'leftDays': 0,
                     'rightDays': 0}],
     'column': 'signal_boll_breakout_upper'},
    {'id': 'broken_limit_up',
     'name': '炸板',
     'kind': 'both',
     'timeframe': 'daily',
     'enabled': True,
     'conditions': [{'left': 'raw_high', 'op': '>', 'right': '0', 'leftDays': 0, 'rightDays': 0},
                    {'left': 'raw_close',
                     'op': '<',
                     'right': 'field:limit_up_price',
                     'leftDays': 0,
                     'rightDays': 0},
                    {'left': 'raw_high',
                     'op': '>=',
                     'right': 'field:limit_up_price',
                     'leftDays': 0,
                     'rightDays': 0}],
     'column': 'signal_broken_limit_up'},
    {'id': 'limit_down',
     'name': '跌停',
     'kind': 'both',
     'timeframe': 'daily',
     'enabled': True,
     'conditions': [{'left': 'raw_close', 'op': '>', 'right': '0', 'leftDays': 0, 'rightDays': 0},
                    {'left': 'raw_close',
                     'op': '<=',
                     'right': 'field:limit_down_price',
                     'leftDays': 0,
                     'rightDays': 0}],
     'column': 'signal_limit_down'},
    {'id': 'limit_down_recovery',
     'name': '跌停翘板',
     'kind': 'both',
     'timeframe': 'daily',
     'enabled': True,
     'conditions': [{'left': 'raw_low', 'op': '>', 'right': '0', 'leftDays': 0, 'rightDays': 0},
                    {'left': 'raw_close',
                     'op': '>',
                     'right': 'field:limit_down_price',
                     'leftDays': 0,
                     'rightDays': 0},
                    {'left': 'raw_low',
                     'op': '<=',
                     'right': 'field:limit_down_price',
                     'leftDays': 0,
                     'rightDays': 0},
                    {'left': 'close', 'op': '>', 'right': 'field:open', 'leftDays': 0, 'rightDays': 0}],
     'column': 'signal_limit_down_recovery'},
    {'id': 'limit_up',
     'name': '涨停',
     'kind': 'both',
     'timeframe': 'daily',
     'enabled': True,
     'conditions': [{'left': 'raw_close', 'op': '>', 'right': '0', 'leftDays': 0, 'rightDays': 0},
                    {'left': 'raw_close',
                     'op': '>=',
                     'right': 'field:limit_up_price',
                     'leftDays': 0,
                     'rightDays': 0}],
     'column': 'signal_limit_up'},
    {'id': 'ma10_breakdown',
     'name': '跌破MA10',
     'kind': 'both',
     'timeframe': 'daily',
     'enabled': True,
     'conditions': [{'left': 'close', 'op': '<', 'right': 'field:ma10', 'leftDays': 0, 'rightDays': 0},
                    {'left': 'close',
                     'op': '>=',
                     'right': 'field:ma10',
                     'leftDays': 1,
                     'rightDays': 1}],
     'column': 'signal_ma10_breakdown'},
    {'id': 'ma10_breakout',
     'name': '突破MA10',
     'kind': 'both',
     'timeframe': 'daily',
     'enabled': True,
     'conditions': [{'left': 'close', 'op': '>', 'right': 'field:ma10', 'leftDays': 0, 'rightDays': 0},
                    {'left': 'close',
                     'op': '<=',
                     'right': 'field:ma10',
                     'leftDays': 1,
                     'rightDays': 1}],
     'column': 'signal_ma10_breakout'},
    {'id': 'ma20_breakdown',
     'name': '跌破MA20',
     'kind': 'both',
     'timeframe': 'daily',
     'enabled': True,
     'conditions': [{'left': 'close', 'op': '<', 'right': 'field:ma20', 'leftDays': 0, 'rightDays': 0},
                    {'left': 'close',
                     'op': '>=',
                     'right': 'field:ma20',
                     'leftDays': 1,
                     'rightDays': 1}],
     'column': 'signal_ma20_breakdown'},
    {'id': 'ma20_breakout',
     'name': '突破MA20',
     'kind': 'both',
     'timeframe': 'daily',
     'enabled': True,
     'conditions': [{'left': 'close', 'op': '>', 'right': 'field:ma20', 'leftDays': 0, 'rightDays': 0},
                    {'left': 'close',
                     'op': '<=',
                     'right': 'field:ma20',
                     'leftDays': 1,
                     'rightDays': 1}],
     'column': 'signal_ma20_breakout'},
    {'id': 'ma5_breakdown',
     'name': '跌破MA5',
     'kind': 'both',
     'timeframe': 'daily',
     'enabled': True,
     'conditions': [{'left': 'close', 'op': '<', 'right': 'field:ma5', 'leftDays': 0, 'rightDays': 0},
                    {'left': 'close', 'op': '>=', 'right': 'field:ma5', 'leftDays': 1, 'rightDays': 1}],
     'column': 'signal_ma5_breakdown'},
    {'id': 'ma5_breakout',
     'name': '突破MA5',
     'kind': 'both',
     'timeframe': 'daily',
     'enabled': True,
     'conditions': [{'left': 'close', 'op': '>', 'right': 'field:ma5', 'leftDays': 0, 'rightDays': 0},
                    {'left': 'close', 'op': '<=', 'right': 'field:ma5', 'leftDays': 1, 'rightDays': 1}],
     'column': 'signal_ma5_breakout'},
    {'id': 'ma_dead_5_20',
     'name': 'MA5下穿MA20',
     'kind': 'both',
     'timeframe': 'daily',
     'enabled': True,
     'conditions': [{'left': 'ma5', 'op': '<', 'right': 'field:ma20', 'leftDays': 0, 'rightDays': 0},
                    {'left': 'ma5', 'op': '>=', 'right': 'field:ma20', 'leftDays': 1, 'rightDays': 1}],
     'column': 'signal_ma_dead_5_20'},
    {'id': 'ma_golden_20_60',
     'name': 'MA20上穿MA60',
     'kind': 'both',
     'timeframe': 'daily',
     'enabled': True,
     'conditions': [{'left': 'ma20', 'op': '>', 'right': 'field:ma60', 'leftDays': 0, 'rightDays': 0},
                    {'left': 'ma20', 'op': '<=', 'right': 'field:ma60', 'leftDays': 1, 'rightDays': 1}],
     'column': 'signal_ma_golden_20_60'},
    {'id': 'ma_golden_5_20',
     'name': 'MA5上穿MA20',
     'kind': 'both',
     'timeframe': 'daily',
     'enabled': True,
     'conditions': [{'left': 'ma5', 'op': '>', 'right': 'field:ma20', 'leftDays': 0, 'rightDays': 0},
                    {'left': 'ma5', 'op': '<=', 'right': 'field:ma20', 'leftDays': 1, 'rightDays': 1}],
     'column': 'signal_ma_golden_5_20'},
    {'id': 'macd_dead',
     'name': 'MACD死叉',
     'kind': 'both',
     'timeframe': 'daily',
     'enabled': True,
     'conditions': [{'left': 'macd_dif',
                     'op': '<',
                     'right': 'field:macd_dea',
                     'leftDays': 0,
                     'rightDays': 0},
                    {'left': 'macd_dif',
                     'op': '>=',
                     'right': 'field:macd_dea',
                     'leftDays': 1,
                     'rightDays': 1}],
     'column': 'signal_macd_dead'},
    {'id': 'macd_golden',
     'name': 'MACD金叉',
     'kind': 'both',
     'conditions': [{'left': 'macd_dif',
                     'op': '>',
                     'right': 'field:macd_dea',
                     'leftDays': 0,
                     'rightDays': 0},
                    {'left': 'macd_dif',
                     'op': '<=',
                     'right': 'field:macd_dea',
                     'leftDays': 1,
                     'rightDays': 1}],
     'enabled': True,
     'timeframe': 'daily',
     'min_bars': 0,
     'column': 'signal_macd_golden'},
    {'id': 'n_day_high',
     'name': '60日新高',
     'kind': 'both',
     'timeframe': 'daily',
     'enabled': True,
     'conditions': [{'left': 'close',
                     'op': '>=',
                     'right': 'field:high_60d',
                     'leftDays': 0,
                     'rightDays': 0}],
     'column': 'signal_n_day_high'},
    {'id': 'n_day_low',
     'name': '60日新低',
     'kind': 'both',
     'timeframe': 'daily',
     'enabled': True,
     'conditions': [{'left': 'close',
                     'op': '<=',
                     'right': 'field:low_60d',
                     'leftDays': 0,
                     'rightDays': 0}],
     'column': 'signal_n_day_low'},
    {'id': 'volume_surge',
     'name': '放量',
     'kind': 'both',
     'timeframe': 'daily',
     'enabled': True,
     'conditions': [{'left': 'vol_ratio_5d', 'op': '>=', 'right': '2', 'leftDays': 0, 'rightDays': 0}],
     'column': 'signal_volume_surge'},
]
